name: Update gist
on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 * * *"
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - name: Update gist
        uses: maxam2017/productive-box@master
        env:
          GH_TOKEN: ${{ secrets.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 }}
          GIST_ID: ${{ secrets.https://gist.github.com/blue4683/ }}
          TIMEZONE: Asia/Seoul
